# Generated by Django 5.2.7 on 2025-10-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_view',
        ),
    ]
